name: Generate Assets

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      # Metrics
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 3e98e0138ac9fe0b509065975b1a2d8f
          plugin_gists: yes
          plugin_notable: yes
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_habits: yes
          plugin_habits_from: 400
          plugin_habits_days: 30
          plugin_habits_facts: yes
          config_timezone: Asia/Manila
      # snk
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-snake.svg?palette=github-dark
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: 3e98e0138ac9fe0b509065975b1a2d8f
          file_path: github-snake.svg
          file_type: binary
