name: Generate assets

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: assets
          plugin_gists: yes
          plugin_notable: yes
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_habits: yes
          plugin_habits_from: 400
          plugin_habits_days: 30
          plugin_habits_facts: yes
          config_timezone: Asia/Manila

  github-contributions-snake:
    runs-on: ubuntu-latest
    needs: github-metrics
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: assets
          fetch-depth: 0
      - uses: fregante/setup-git-user@v1

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: sitiom
          gif_out_path: github-contribution-grid-snake.gif
          svg_out_path: github-contribution-grid-snake.svg
          
      - name: Squash and Commit
        run : |
          git add .
          git reset --soft HEAD~2
          git commit -m "Update assets - [Skip GitHub Action]"
          git push -f
