name: metrics

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
